### ISSUE TITLE
boa tarde Ericson

### ISSUE THREAD

**Issue by brunoorosco** [ericsonscodeler/palpite-box#2]
eu vi no seu repositório que possivelmente vc tem os videos da semana full-stack master, como eu não consegui acompanhar, é possível você compartilhar comigo? Desculpe o pedido!
brunoorosco@gmail.com

**Comment by ericsonscodeler** [comment]
opa boa tarde, vou subir no drive e compartilho com voce !

**Comment by brunoorosco** [comment]
Muito Obrigado!!!



*att.,Bruno Orosco*
Profº Esp. em Automação Industrial
www.orostec.blogspot.com.br


Em ter., 14 de jul. de 2020 às 13:30, Ericson Scodeler <
notifications@github.com> escreveu:
